### PR TITLE
Search page refactor

### LINKED ISSUE #72: Add search to listing pages

### LINKED ISSUE #95: Improve the search story
We need to review the search story and improve the UX.

The following examples are performed on the IDN instance of Prez, but it should apply for all Prez instances.

https://data.idnau.org

For example, when I search "indigenous" in the global search bar, this is the result.

Screenshot 2023-08-15 at 3 00 01 pm

Next step I do is change the subsystem to "CatPrez" and use the default "Exact Match" search method and searched again.

Screenshot 2023-08-15 at 3 01 46 pm

To get a successful search result, I then change the search method to "Jena F T Name" and searched again.

Screenshot 2023-08-15 at 3 04 09 pm

In this instance, we should make "Jena F T Name" the default search method. A solution could be to make Prez UI query what search methods are available in the Prez API backend and choose the best performing search method as the default search behaviour. "Best" is probably subjective and can be something that's configured by the Prez admin in the configuration.

### PR DESCRIPTION
**Pull request by jamiefeiss**
The search page now uses the new search implementation outlined in https://github.com/RDFLib/prez/pull/149.

Users can filter by a base class, containers, and can provide custom inbound & outbound filters.

image

Resolves #95, resolves #72.

### CODE REVIEW

**Comment by recalcitrantsupplant** [comment]
I've tested locally, looks good, only one minor issue:
As the current backend MVP search doesn't allow UNION across different filter conditions, rather it's an AND, if a user tries to search in two kinds of Container class, most likely results do not exist as instances of both Container class, so they'll get no results. For example restricting to search within datasets only yields a result:

image

Searching within a dataset and a vocabulary yields no result:

image

The assumption here is a user would expect when ticking multiple Container instances, results can come from within any instance, not that the result must exist in all of them.

I'd make the following recommendations for non-MVP enhancements:
- tick all Container options and Containers by default - or have a special "select all" option at the top so it's clear everything is searched by default. When the query is sent to the backend, if it's a "select all" then the filter could be left off altogether, I think you've previously suggested this.
- Make it clear which label properties/predicates are being searched. At present this is label, description, and provenance (yes, the backend still needs to expose this information ..)
- Display the object class using a label rather than URI
- Presumably searching within a Container should include all objects that are transitively within it - e.g. Features within a Dataset - something for us to discuss tomorrow. We'd need to update the backend to support this first though.

**Review by recalcitrantsupplant — CHANGES_REQUESTED** [review]
see comments above

**Comment by jamiefeiss** [comment]
@recalcitrantsupplant thanks for the comments. What changes would you suggest for this MVP now? I could start by adding to the page that you can't select multiple container types.

**Comment by recalcitrantsupplant** [comment]
Just the one to restrict searching to one container _type_ at present

**Review by recalcitrantsupplant — DISMISSED** [review]

**Comment by jamiefeiss** [comment]
Added pagination using https://github.com/RDFLib/prez/pull/159

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
