### PR TITLE
This update provides basic UI map search functionality to the SpacePrez subsystem.

### PR DESCRIPTION
**Pull request by hjohns**
Map search features:
- Ability to select a point, rectangle or polygon on a google map
- Select an area type to search - nearby, contains, overlaps, within
- Selection of one or more feature collections within the available datasets
- Limiting of the number of results
- Show query - displays the generated SPARQL query to get map search results

Full details of changes are in the changelog.md file.

### CODE REVIEW

**Comment by hjohns** [comment]
@jamiefeiss @nicholascar - I can't assign you as reviews, can you please review? Thanks.

**Review by nicholascar — APPROVED** [review]
Fine by me but I'm flying a bit blind here! @jamiefeiss over to you! Happy to push through to seeing a public instance up for more testing.

**Comment by jamiefeiss** [comment]
Everything looks pretty good, the map search is nice and snappy and works well.

Changes to be made following a chat with @hjohns:

- Fix TypeScript build errors
- Select all datasets & feature collections by default in SpacePrezSearchMap
- Render the search results list underneath the map
- Add a line in the map search query for prez:link (/object?uri=... endpoint in API is not currently working)

**Comment by hjohns** [comment]
@jamiefeiss updates completed as requested, with a caveat around the typescript errors for the google map integration, but should be fixed else where. Ok if we merge this one in if it looks ok, to get the main changes in. Can follow up the other typescript errors in a follow up issue, if that's ok.

**Review by jamiefeiss — APPROVED** [review]

**Pull request merged**
